-- Supabase PostgreSQL Schema

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Courses Table
CREATE TABLE IF NOT EXISTS courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university TEXT NOT NULL,
  course_code TEXT NOT NULL,
  title TEXT NOT NULL,
  units TEXT,
  credit DOUBLE PRECISION,
  description TEXT,
  url TEXT,
  details JSONB,
  instructors TEXT[] DEFAULT '{}'::text[],
  prerequisites TEXT,
  related_urls TEXT[] DEFAULT '{}'::text[],
  cross_listed_courses TEXT,
  department TEXT,
  corequisites TEXT,
  level TEXT,
  difficulty DOUBLE PRECISION,
  popularity INTEGER DEFAULT 0,
  workload DOUBLE PRECISION,
  subdomain TEXT,
  resources TEXT[] DEFAULT '{}'::text[],
  category TEXT,
  is_hidden BOOLEAN DEFAULT FALSE,
  is_internal BOOLEAN DEFAULT FALSE,
  latest_semester JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(university, course_code)
);

CREATE INDEX IF NOT EXISTS idx_courses_university ON courses(university);
CREATE INDEX IF NOT EXISTS idx_courses_course_code ON courses(course_code);
CREATE INDEX IF NOT EXISTS idx_courses_popularity ON courses(popularity DESC);
CREATE INDEX IF NOT EXISTS idx_courses_subdomain ON courses(subdomain);
CREATE INDEX IF NOT EXISTS idx_courses_category ON courses(category);
CREATE INDEX IF NOT EXISTS idx_courses_created_at ON courses(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_courses_title ON courses(title);

-- Full-text search support
ALTER TABLE courses ADD COLUMN IF NOT EXISTS search_vector tsvector
  GENERATED ALWAYS AS (
    to_tsvector('english', coalesce(title,'') || ' ' || coalesce(course_code,'') || ' ' || coalesce(description,''))
  ) STORED;
CREATE INDEX IF NOT EXISTS idx_courses_search ON courses USING GIN(search_vector);

-- Fields Table
CREATE TABLE IF NOT EXISTS fields (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

-- Course-Fields Relationship
CREATE TABLE IF NOT EXISTS course_fields (
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  field_id BIGINT NOT NULL REFERENCES fields(id) ON DELETE CASCADE,
  PRIMARY KEY (course_id, field_id)
);

CREATE INDEX IF NOT EXISTS idx_course_fields_field ON course_fields(field_id);

-- User Courses Table (Linking to Supabase Auth)
CREATE TABLE IF NOT EXISTS user_courses (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  status TEXT DEFAULT 'pending', -- pending, in_progress, completed, dropped
  priority INTEGER DEFAULT 0,
  gpa NUMERIC(3,2) CHECK (gpa >= 0 AND gpa <= 5.0),
  score NUMERIC(5,2) CHECK (score >= 0 AND score <= 100),
  notes TEXT,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (user_id, course_id)
);

CREATE INDEX IF NOT EXISTS idx_user_courses_user ON user_courses(user_id);
CREATE INDEX IF NOT EXISTS idx_user_courses_status ON user_courses(status);
CREATE INDEX IF NOT EXISTS idx_user_courses_user_status ON user_courses(user_id, status);

-- Profiles Table
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  ai_provider TEXT NOT NULL DEFAULT 'perplexity',
  ai_default_model TEXT NOT NULL DEFAULT 'sonar',
  ai_web_search_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ai_prompt_template TEXT,
  ai_study_plan_prompt_template TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Semesters Table
CREATE TABLE IF NOT EXISTS semesters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INTEGER NOT NULL,
  term TEXT NOT NULL,
  UNIQUE(year, term)
);

-- Course-Semesters Relationship
CREATE TABLE IF NOT EXISTS course_semesters (
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  PRIMARY KEY (course_id, semester_id)
);

CREATE INDEX IF NOT EXISTS idx_course_semesters_semester ON course_semesters(semester_id);

-- Study Plans Table
-- Stores user's study rules (e.g., Mon/Wed/Fri from 9-11am)
CREATE TABLE IF NOT EXISTS study_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  type TEXT DEFAULT 'lecture', -- lecture, exercise, exam, etc.
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  days_of_week INTEGER[] NOT NULL, -- 0=Sun, 1=Mon, ..., 6=Sat
  start_time TIME NOT NULL DEFAULT '09:00:00',
  end_time TIME NOT NULL DEFAULT '11:00:00',
  location TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_study_plans_user ON study_plans(user_id);
CREATE INDEX IF NOT EXISTS idx_study_plans_dates ON study_plans(start_date, end_date);

-- Study Logs Table
-- Stores specific instances (exceptions, completions) for generated events
CREATE TABLE IF NOT EXISTS study_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  plan_id BIGINT NOT NULL REFERENCES study_plans(id) ON DELETE CASCADE,
  log_date DATE NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, plan_id, log_date)
);

CREATE INDEX IF NOT EXISTS idx_study_logs_user_date ON study_logs(user_id, log_date);

-- Scraper Background Queue
CREATE TABLE IF NOT EXISTS scraper_jobs (
  id SERIAL PRIMARY KEY,
  university TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'completed', 'failed')),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  error TEXT,
  course_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_scraper_jobs_status ON scraper_jobs(status, created_at);

-- Workouts Table: Sport/fitness courses from university workout centers
CREATE TABLE IF NOT EXISTS workouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL,
  course_code TEXT NOT NULL,
  category TEXT NOT NULL,
  category_en TEXT,
  title TEXT NOT NULL,
  title_en TEXT,
  day_of_week TEXT,
  start_time TIME,
  end_time TIME,
  location TEXT,
  location_en TEXT,
  instructor TEXT,
  start_date DATE,
  end_date DATE,
  price_student NUMERIC(6,2),
  price_staff NUMERIC(6,2),
  price_external NUMERIC(6,2),
  price_external_reduced NUMERIC(6,2),
  booking_status TEXT,
  booking_url TEXT,
  url TEXT,
  semester TEXT,
  details JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(source, course_code)
);

CREATE INDEX IF NOT EXISTS idx_workouts_source ON workouts(source);
CREATE INDEX IF NOT EXISTS idx_workouts_category ON workouts(category);
CREATE INDEX IF NOT EXISTS idx_workouts_day_of_week ON workouts(day_of_week);
CREATE INDEX IF NOT EXISTS idx_workouts_booking_status ON workouts(booking_status);
CREATE INDEX IF NOT EXISTS idx_workouts_semester ON workouts(semester);

ALTER TABLE workouts ADD COLUMN IF NOT EXISTS search_vector tsvector
  GENERATED ALWAYS AS (
    to_tsvector('simple', coalesce(title,'') || ' ' || coalesce(title_en,'') || ' ' || coalesce(category,'') || ' ' || coalesce(category_en,''))
  ) STORED;
CREATE INDEX IF NOT EXISTS idx_workouts_search ON workouts USING GIN(search_vector);

-- Row Level Security (RLS)
-- ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE fields ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE course_fields ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE semesters ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE course_semesters ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE workouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_logs ENABLE ROW LEVEL SECURITY;

-- Policies: Public Read Access (only for tables with RLS enabled)
-- CREATE POLICY "Allow public read access on courses" ON courses FOR SELECT USING (NOT is_hidden);
-- CREATE POLICY "Allow public read access on fields" ON fields FOR SELECT USING (true);
-- CREATE POLICY "Allow public read access on course_fields" ON course_fields FOR SELECT USING (true);
-- CREATE POLICY "Allow public read access on semesters" ON semesters FOR SELECT USING (true);
-- CREATE POLICY "Allow public read access on course_semesters" ON course_semesters FOR SELECT USING (true);
-- CREATE POLICY "Allow public read access on workouts" ON workouts FOR SELECT USING (true);

-- Ensure all roles can access the disabled RLS tables
GRANT ALL ON TABLE courses TO anon, authenticated, service_role;
GRANT ALL ON TABLE workouts TO anon, authenticated, service_role;
GRANT ALL ON TABLE fields TO anon, authenticated, service_role;
GRANT ALL ON TABLE semesters TO anon, authenticated, service_role;
GRANT ALL ON TABLE course_fields TO anon, authenticated, service_role;
GRANT ALL ON TABLE course_semesters TO anon, authenticated, service_role;

-- Policies: Authenticated User Access for user_courses
CREATE POLICY "Users can view their own enrollments" ON user_courses FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own enrollments" ON user_courses FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own enrollments" ON user_courses FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own enrollments" ON user_courses FOR DELETE USING (auth.uid() = user_id);

-- Policies: Profiles
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Policies: Study Plans
CREATE POLICY "Users can view their own plans" ON study_plans FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own plans" ON study_plans FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own plans" ON study_plans FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own plans" ON study_plans FOR DELETE USING (auth.uid() = user_id);

-- Policies: Study Logs
CREATE POLICY "Users can view their own logs" ON study_logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own logs" ON study_logs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own logs" ON study_logs FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own logs" ON study_logs FOR DELETE USING (auth.uid() = user_id);

-- RPC Functions
CREATE OR REPLACE FUNCTION increment_popularity(row_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE courses
  SET popularity = popularity + 1
  WHERE id = row_id;
END;
$$;
