import type { TranscriptRow } from "./transcript";

interface TranscriptTypstInput {
  title: string;
  rows: TranscriptRow[];
  generatedBy: string;
  universityFilter: string;
  semesterFilter: string;
}

function escapeTypstString(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"");
}

function formatDate(value?: string): string {
  if (!value) return "-";
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return "-";
  return d.toLocaleDateString("en-US");
}

function averageScore(rows: TranscriptRow[]): string {
  const withScore = rows.filter((r) => typeof r.score === "number");
  if (withScore.length === 0) return "-";
  const avg = withScore.reduce((sum, r) => sum + (r.score || 0), 0) / withScore.length;
  return avg.toFixed(2);
}

function toTypstRows(rows: TranscriptRow[]): string {
  return rows
    .map((row, index) => {
      const semesters = (row.semesters || []).join(", ") || "-";
      const credit = row.credit !== undefined ? String(row.credit) : "-";
      const gpa = row.gpa !== undefined ? row.gpa.toFixed(2) : "-";
      const score = row.score !== undefined ? `${row.score.toFixed(1)}%` : "-";
      return `(
  no: "${index + 1}",
  code: "${escapeTypstString(row.courseCode || "-")}",
  title: "${escapeTypstString(row.title || "-")}",
  university: "${escapeTypstString(row.university || "-")}",
  credit: "${escapeTypstString(credit)}",
  gpa: "${escapeTypstString(gpa)}",
  score: "${escapeTypstString(score)}",
  semester: "${escapeTypstString(semesters)}",
  completed: "${escapeTypstString(formatDate(row.completionDate))}",
)`;
    })
    .join(",\n");
}

export function buildTranscriptTypst(input: TranscriptTypstInput): string {
  const rowsExpr = toTypstRows(input.rows);
  const now = new Date().toLocaleString("en-US");
  const avgScore = averageScore(input.rows);

  return `#set page(
  paper: "a4",
  margin: (x: 1.5cm, y: 1.2cm),
  numbering: "1",
)

#set text(font: "Libertinus Serif", size: 10pt)
#set par(justify: false)

#let title_text = "${escapeTypstString(input.title)}"
#let university_filter = "${escapeTypstString(input.universityFilter)}"
#let semester_filter = "${escapeTypstString(input.semesterFilter)}"
#let generated_at = "${escapeTypstString(now)}"
#let generated_by = "${escapeTypstString(input.generatedBy)}"
#let record_count = "${escapeTypstString(String(input.rows.length))}"
#let average_score = "${escapeTypstString(avgScore)}"

#let rows = (
${rowsExpr}
)

#align(center, [
  #text(size: 18pt, weight: "bold")[Academic Transcript]
  \\ #text(size: 9pt, fill: rgb("#666"))[CodeCampus Export]
])

#v(8pt)
#grid(
  columns: (2.8cm, 1fr, 2.8cm, 1fr),
  gutter: 6pt,
  [#text(weight: "bold")[Title:]], [#title_text],
  [#text(weight: "bold")[University:]], [#university_filter],
  [#text(weight: "bold")[Semester:]], [#semester_filter],
  [#text(weight: "bold")[Generated:]], [#generated_at],
  [#text(weight: "bold")[Generated by:]], [#generated_by],
  [#text(weight: "bold")[Records:]], [#record_count],
  [#text(weight: "bold")[Avg Score:]], [#average_score],
)

#v(10pt)

#table(
  columns: (0.8cm, 1.8cm, 4.4cm, 2.0cm, 1.2cm, 1.1cm, 1.4cm, 2.0cm, 1.9cm),
  align: (x, y) => if y == 0 { center } else if x >= 4 { right } else { left },
  inset: 4pt,
  stroke: 0.35pt + rgb("#d0d0d0"),
  fill: (x, y) => if y == 0 { rgb("#f3f5f8") } else { white },

  [#text(weight: "bold")[#]],
  [#text(weight: "bold")[Code]],
  [#text(weight: "bold")[Course]],
  [#text(weight: "bold")[University]],
  [#text(weight: "bold")[Cred]],
  [#text(weight: "bold")[GPA]],
  [#text(weight: "bold")[Score]],
  [#text(weight: "bold")[Semester]],
  [#text(weight: "bold")[Completed]],

  ..rows.map(r => (
    [#r.no],
    [#r.code],
    [#r.title],
    [#r.university],
    [#r.credit],
    [#r.gpa],
    [#r.score],
    [#r.semester],
    [#r.completed],
  )).flatten(),
)

#v(8pt)
#text(size: 8.5pt, fill: rgb("#666"))[
  This document is generated by CodeCampus for personal academic tracking.
]
`;
}
