import React from 'react';

interface FormattedDescriptionProps {
  text: string;
}

type BlockType = 'header' | 'list' | 'paragraph' | 'signature' | 'empty';

interface Block {
  type: BlockType;
  content: string[];
}

export default function FormattedDescription({ text }: FormattedDescriptionProps) {
  if (!text) return null;

  const lines = text.split('\n');
  const blocks: Block[] = [];
  let currentBlock: Block | null = null;

  const flushBlock = () => {
    if (currentBlock && currentBlock.content.length > 0) {
      blocks.push(currentBlock);
    }
    currentBlock = null;
  };

  lines.forEach((line) => {
    const trimmed = line.trim();

    // 1. Signature Check
    if (trimmed === "Regenerated by Gemini" || trimmed === "*Regenerated by Gemini*") {
      flushBlock();
      blocks.push({ type: 'signature', content: [trimmed] });
      return;
    }

    // 2. Empty Line -> Flush
    if (!trimmed) {
      flushBlock();
      return;
    }

    // 3. List Item Detection (•, -, *)
    const isListItem = /^[•\-\*]\s/.test(trimmed) || /^\d+\.\s/.test(trimmed);
    if (isListItem) {
      if (currentBlock && currentBlock.type !== 'list') {
        flushBlock();
      }
      if (!currentBlock) {
        currentBlock = { type: 'list', content: [] };
      }
      currentBlock.content.push(trimmed.replace(/^[•\-\*]\s*/, '').replace(/^\d+\.\s*/, ''));
      return;
    }

    // 4. Header Detection
    // Criteria: Short (< 60 chars), no end punctuation (except colon), or ALL CAPS
    // Exclude common sentence starters to avoid false positives if possible
    const isHeader = 
      (trimmed.length < 60 && !/[.,;!]$/.test(trimmed)) || 
      /^[A-Z\s\(\)\-\:&]+$/.test(trimmed) ||
      trimmed.endsWith(':');

    if (isHeader) {
      flushBlock();
      // Headers are single lines usually
      blocks.push({ type: 'header', content: [trimmed.replace(/:$/, '')] });
      return;
    }

    // 5. Paragraph
    if (currentBlock && currentBlock.type !== 'paragraph') {
      flushBlock();
    }
    if (!currentBlock) {
      currentBlock = { type: 'paragraph', content: [] };
    }
    currentBlock.content.push(trimmed);
  });

  flushBlock();

  return (
    <div className="space-y-6 font-sans text-gray-600">
      {blocks.map((block, index) => {
        if (block.type === 'signature') {
          return (
            <div key={index} className="flex items-center gap-2 mt-8 pt-6 border-t border-gray-100">
               <div className="h-px flex-1 bg-gradient-to-r from-transparent via-brand-blue/20 to-transparent"></div>
               <span className="text-[10px] font-black text-brand-blue uppercase tracking-widest italic">
                 ✨ Enhanced by Gemini AI
               </span>
               <div className="h-px flex-1 bg-gradient-to-r from-transparent via-brand-blue/20 to-transparent"></div>
            </div>
          );
        }

        if (block.type === 'header') {
          return (
            <h3 key={index} className="text-[13px] font-black text-gray-900 uppercase tracking-[0.2em] pt-6 border-b-2 border-brand-blue/10 pb-2 w-max pr-8">
              {block.content[0]}
            </h3>
          );
        }

        if (block.type === 'list') {
          return (
            <ul key={index} className="grid gap-4 pl-2">
              {block.content.map((item, i) => (
                <li key={i} className="flex items-start gap-4 text-[17px] leading-relaxed">
                  <span className="w-1.5 h-1.5 mt-2.5 rounded-full bg-brand-blue/60 flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          );
        }

        // Paragraph
        return (
          <p key={index} className="text-[17px] leading-8 text-gray-600 font-medium">
            {block.content.join(' ')}
          </p>
        );
      })}
    </div>
  );
}
