CREATE TABLE IF NOT EXISTS public.ai_planner_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  preset TEXT,
  response JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.ai_planner_responses
  ADD COLUMN IF NOT EXISTS feature TEXT NOT NULL DEFAULT 'planner',
  ADD COLUMN IF NOT EXISTS provider TEXT,
  ADD COLUMN IF NOT EXISTS model TEXT,
  ADD COLUMN IF NOT EXISTS prompt TEXT,
  ADD COLUMN IF NOT EXISTS response_text TEXT,
  ADD COLUMN IF NOT EXISTS request_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS response_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS tokens_input INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tokens_output INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cost_usd NUMERIC(12, 6) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_ai_planner_responses_user_created
  ON public.ai_planner_responses (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ai_planner_responses_feature_created
  ON public.ai_planner_responses (feature, created_at DESC);

