CREATE TABLE IF NOT EXISTS public.course_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
  syllabus_id BIGINT NULL REFERENCES public.course_syllabi(id) ON DELETE SET NULL,
  schedule_date DATE NOT NULL,
  focus TEXT NULL,
  task_kind TEXT NULL,
  task_title TEXT NOT NULL,
  duration_minutes INTEGER NULL,
  source TEXT NOT NULL DEFAULT 'ai_course_intel',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  retrieved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_course_schedules_dedupe
ON public.course_schedules (
  course_id,
  schedule_date,
  lower(task_title),
  COALESCE(task_kind, ''),
  source
);

CREATE INDEX IF NOT EXISTS idx_course_schedules_course_id
  ON public.course_schedules(course_id);

CREATE INDEX IF NOT EXISTS idx_course_schedules_schedule_date
  ON public.course_schedules(schedule_date);

ALTER TABLE public.course_schedules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated users can read course_schedules"
ON public.course_schedules
FOR SELECT
TO authenticated
USING (true);

ALTER TABLE public.course_assignments
ADD COLUMN IF NOT EXISTS course_schedule_id BIGINT NULL REFERENCES public.course_schedules(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_course_assignments_course_schedule_id
  ON public.course_assignments(course_schedule_id);
