-- Workouts Table: Sport/fitness courses from university workout centers
CREATE TABLE IF NOT EXISTS workouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL,                          -- e.g. 'CAU Kiel Sportzentrum'
  course_code TEXT NOT NULL,                     -- e.g. '1430-01'
  category TEXT NOT NULL,                        -- German category e.g. 'Yoga, Hatha Yoga'
  category_en TEXT,                              -- English translation
  title TEXT NOT NULL,                           -- German title e.g. 'Yoga, Hatha Yoga Grundstufe'
  title_en TEXT,                                 -- English translation
  day_of_week TEXT,                              -- e.g. 'Mon' or 'Tue, Thu'
  start_time TIME,                               -- e.g. 17:30
  end_time TIME,                                 -- e.g. 19:00
  location TEXT,                                 -- German venue name
  location_en TEXT,                              -- English translation
  instructor TEXT,                               -- instructor name(s)
  start_date DATE,                               -- period start
  end_date DATE,                                 -- period end
  price_student NUMERIC(6,2),                    -- student price
  price_staff NUMERIC(6,2),                      -- staff/alumni price
  price_external NUMERIC(6,2),                   -- external price
  price_external_reduced NUMERIC(6,2),           -- external reduced price
  booking_status TEXT,                           -- 'available', 'fully_booked', 'expired', 'waitlist', 'cancelled', 'see_text', 'unknown'
  booking_url TEXT,                              -- direct booking link
  url TEXT,                                      -- course detail page URL
  semester TEXT,                                 -- e.g. 'WiSe 25/26'
  details JSONB DEFAULT '{}'::jsonb,             -- extra data (multi-day schedules, etc.)
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(source, course_code)
);

CREATE INDEX IF NOT EXISTS idx_workouts_source ON workouts(source);
CREATE INDEX IF NOT EXISTS idx_workouts_category ON workouts(category);
CREATE INDEX IF NOT EXISTS idx_workouts_day_of_week ON workouts(day_of_week);
CREATE INDEX IF NOT EXISTS idx_workouts_booking_status ON workouts(booking_status);
CREATE INDEX IF NOT EXISTS idx_workouts_semester ON workouts(semester);

-- Full-text search on title and category (both DE and EN)
ALTER TABLE workouts ADD COLUMN IF NOT EXISTS search_vector tsvector
  GENERATED ALWAYS AS (
    to_tsvector('simple', coalesce(title,'') || ' ' || coalesce(title_en,'') || ' ' || coalesce(category,'') || ' ' || coalesce(category_en,''))
  ) STORED;
CREATE INDEX IF NOT EXISTS idx_workouts_search ON workouts USING GIN(search_vector);

-- RLS
ALTER TABLE workouts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on workouts" ON workouts FOR SELECT USING (true);
