ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS ai_course_intel_prompt_template TEXT;

CREATE TABLE IF NOT EXISTS public.course_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
  syllabus_id BIGINT NULL REFERENCES public.course_syllabi(id) ON DELETE SET NULL,
  kind TEXT NOT NULL CHECK (kind IN ('assignment', 'lab', 'exam', 'project', 'quiz', 'other')),
  label TEXT NOT NULL,
  due_on DATE NULL,
  url TEXT NULL,
  description TEXT NULL,
  source_sequence TEXT NULL,
  source_row_date DATE NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  retrieved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_course_assignments_dedupe
ON public.course_assignments (
  course_id,
  kind,
  lower(label),
  COALESCE(due_on, DATE '0001-01-01')
);

CREATE INDEX IF NOT EXISTS idx_course_assignments_course_id
  ON public.course_assignments(course_id);

CREATE INDEX IF NOT EXISTS idx_course_assignments_due_on
  ON public.course_assignments(due_on);

ALTER TABLE public.course_assignments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated users can read course_assignments"
ON public.course_assignments
FOR SELECT
TO authenticated
USING (true);
