create table if not exists public.user_workout_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  workout_id bigint not null references public.workouts(id) on delete cascade,
  log_date date not null,
  is_attended boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, workout_id, log_date)
);

create index if not exists user_workout_logs_user_id_idx on public.user_workout_logs (user_id);
create index if not exists user_workout_logs_workout_id_idx on public.user_workout_logs (workout_id);
create index if not exists user_workout_logs_log_date_idx on public.user_workout_logs (log_date);

alter table public.user_workout_logs enable row level security;

create policy "user_workout_logs_select_own"
on public.user_workout_logs
for select
using (auth.uid() = user_id);

create policy "user_workout_logs_insert_own"
on public.user_workout_logs
for insert
with check (auth.uid() = user_id);

create policy "user_workout_logs_update_own"
on public.user_workout_logs
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "user_workout_logs_delete_own"
on public.user_workout_logs
for delete
using (auth.uid() = user_id);
