CREATE TABLE IF NOT EXISTS public.course_syllabi (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id    INTEGER NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
  source_url   TEXT,
  raw_text     TEXT,
  content      JSONB NOT NULL DEFAULT '{}'::jsonb,
  schedule     JSONB NOT NULL DEFAULT '[]'::jsonb,
  retrieved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.course_syllabi
  ADD CONSTRAINT course_syllabi_course_id_key UNIQUE (course_id);

CREATE INDEX IF NOT EXISTS idx_course_syllabi_course_id
  ON public.course_syllabi (course_id);
