-- Table for specialized academic activities like Projects, Seminars, Colloquia, etc.
-- This separates high-level/research-oriented activities from standard course lectures.

CREATE TABLE IF NOT EXISTS projects_seminars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university TEXT NOT NULL,
  course_code TEXT NOT NULL,
  category TEXT NOT NULL, -- e.g., 'Seminar', 'Advanced Project', 'Colloquium'
  title TEXT NOT NULL,
  description TEXT,
  url TEXT,
  instructors TEXT[] DEFAULT '{}'::text[],
  credit DOUBLE PRECISION,
  latest_semester JSONB,
  details JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(university, course_code)
);

CREATE INDEX IF NOT EXISTS idx_projsem_university ON projects_seminars(university);
CREATE INDEX IF NOT EXISTS idx_projsem_category ON projects_seminars(category);

-- Full-text search support
ALTER TABLE projects_seminars ADD COLUMN IF NOT EXISTS search_vector tsvector
  GENERATED ALWAYS AS (
    to_tsvector('english', coalesce(title,'') || ' ' || coalesce(course_code,'') || ' ' || coalesce(description,''))
  ) STORED;
CREATE INDEX IF NOT EXISTS idx_projsem_search ON projects_seminars USING GIN(search_vector);

-- Disable RLS for local development scraping (matches courses table)
ALTER TABLE projects_seminars DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE projects_seminars TO anon, authenticated, service_role;
